Repository kapi2289/vulcan-api, pull requests merged in 2020-10, with the labels that each got.

#38 Add `visible` Lesson attribute
  vulcan/_lesson.py
Labels: enhancement, hacktoberfest

#41 Fix problems with request signing.
  vulcan/_api.py
  vulcan/_certificate.py
  vulcan/_utils.py
Labels: bug, hacktoberfest

#39 Add attendance support, add option to set device name
  vulcan/_attendance.py
  vulcan/_certificate.py
  vulcan/_vulcan.py
Labels: enhancement, hacktoberfest

#42 Fix date filtering.
  vulcan/_utils.py
Labels: bug, hacktoberfest

#44 Update documentation.
  docs/source/full-docs.rst
  docs/source/getting-started/basic-usage.rst
  docs/source/getting-started/registration.rst
  vulcan/_attendance.py
  vulcan/_certificate.py
  vulcan/_class.py
  vulcan/_dictionaries.py
  vulcan/_exam.py
  vulcan/_grade.py
  vulcan/_homework.py
  vulcan/_lesson.py
  vulcan/_message.py
  vulcan/_notice.py
  vulcan/_period.py
  vulcan/_school.py
  vulcan/_student.py
  vulcan/_subject.py
  vulcan/_teacher.py
  vulcan/_vulcan.py
Labels: documentation, hacktoberfest

#40 Add support for message sending.
  vulcan/_dictionaries.py
  vulcan/_message.py
  vulcan/_student.py
  vulcan/_teacher.py
  vulcan/_vulcan.py
Labels: enhancement, hacktoberfest

#45 Change attendance subject attribute to Subject object instead of subject name.
  vulcan/_attendance.py
Labels: hacktoberfest

#46 Add attendance and message tests.
  tests/test_attendance.py
  tests/test_messages.py
  tests/utils.py
  vulcan/_attendance.py
Labels: hacktoberfest, testing
