Repository kapi2289/vulcan-api, pull requests merged in 2021-04, with the labels that each got.

#80 Add support for fetching messages, Improve errors handling
  docs/source/full-docs.rst
  vulcan/_api.py
  vulcan/_data.py
  vulcan/data/__init__.py
  vulcan/data/_message.py
Labels: enhancement

#85 Fix messages docs
  vulcan/data/_message.py
Labels: documentation

#84 Replace Travis with GitHub Actions
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  pytest.ini
  requirements.txt
Labels: testing
